apiVersion: v1
kind: Pod
metadata:
  name: tsc003-download-files
  namespace: cyberarch

spec:
  containers:
    - name: work-container
      image: tsekai/a2bs_base:latest # docker image
      # imagePullPolicy: Always
      command:
            - bash
            - -c
            - |
              source /usr/local/bin/_activate_current_env.sh
              git clone https://github.com/t-sekai/a2bs.git
              pip install -r a2bs/requirements.txt
              echo "done setup"
              sleep infinity
      resources:
        requests:
          cpu: "10"
          memory: "20Gi"
          nvidia.com/gpu: "1"
        limits:
          cpu: "10"
          memory: "20Gi"
          nvidia.com/gpu: "1"
      volumeMounts:
        - name: tsc003-beat-vol
          mountPath: /tsc003-beat-vol
  volumes:
    - name: tsc003-beat-vol
      persistentVolumeClaim:
        claimName: tsc003-beat-vol
  restartPolicy: Never
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: nvidia.com/gpu.product
              operator: In
              values:
                - NVIDIA-GeForce-RTX-4090